 
New instance of bashtop version: 0.9.25 Pid: 124929
PSUTIL ERROR! Command: get_disks(exclude='squashfs')
not sure how to interpret line ' 259       0 nvme1n1 222 0 16864 96 4 0 0 2 0 116 100 0 0 0 0 4 2\n'
 
New instance of bashtop version: 0.9.25 Pid: 9202
 
New instance of bashtop version: 0.9.25 Pid: 6441
Traceback (most recent call last):
  File "/tmp/2d8hx2WldUaS/bashtop.psutil", line 395, in <module>
    exec(command)
  File "<string>", line 1, in <module>
  File "/tmp/2d8hx2WldUaS/bashtop.psutil", line 224, in get_proc
    for p in sorted(psutil.process_iter(['pid', 'name', 'cmdline', 'num_threads', 'username', 'memory_percent', 'cpu_percent', 'cpu_times', 'create_time'], err), key=lambda p: eval(sort_cmd), reverse=reverse):
  File "/usr/lib64/python3.9/site-packages/psutil/__init__.py", line 1463, in process_iter
    if proc.is_running():
  File "/usr/lib64/python3.9/site-packages/psutil/__init__.py", line 598, in is_running
    return self == Process(self.pid)
  File "/usr/lib64/python3.9/site-packages/psutil/__init__.py", line 343, in __init__
    self._init(pid)
  File "/usr/lib64/python3.9/site-packages/psutil/__init__.py", line 371, in _init
    self.create_time()
  File "/usr/lib64/python3.9/site-packages/psutil/__init__.py", line 727, in create_time
    self._create_time = self._proc.create_time()
  File "/usr/lib64/python3.9/site-packages/psutil/_pslinux.py", line 1515, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/psutil/_pslinux.py", line 1727, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/usr/lib64/python3.9/site-packages/psutil/_pslinux.py", line 1515, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib64/python3.9/site-packages/psutil/_common.py", line 452, in wrapper
    return fun(self)
KeyboardInterrupt
/usr/bin/bashtop: line 4806: ${pycoproc[1]}: ambiguous redirect
 
New instance of bashtop version: 0.9.25 Pid: 21714
